[project]
name = "yysrobot"
version = "0.1.0"
description = "yysrobot"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    
]
plugins = []
plugin_dirs = []
builtin_plugins = []
